### ISSUE TITLE
day is out of range

### ISSUE THREAD

**Issue by uescher** [byro/byro#100]
Mitglieder die am [29.-31.] eingetreten sind, können im Februar nicht fehlerfrei austreten. 
```
ERROR 2019-02-19 18:25:19,281 django.request exception Internal Server Error: /members/view/123/leave
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/code/byro/office/views/members.py", line 237, in post
    form.instance.member.update_liabilites()
  File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/opt/code/byro/members/models.py", line 179, in update_liabilites
    booking_date = _now.replace(day=membership.start.day)
ValueError: day is out of range for month
```

**Comment by henryk** [comment]
Ohh, funky issue. What would the 'right' solution be here? Just use https://stackoverflow.com/questions/2249956/how-to-get-the-same-day-of-next-month-of-a-given-day-in-python-using-datetime/2251203#2251203 ?

**Comment by rixx** [comment]
The right solution is to use dateutil, which we rely on already.

**Comment by rixx** [comment]
Using dateutil is pretty much always the right idea with non-standard Python datetime operations.
