### ISSUE TITLE
Installation error during compress step

### ISSUE THREAD

**Issue by MoritzFago** [byro/byro#124]
I tried to follow the administrator documentation and build an ansible playbook from that.
That was unfortunately challenging, the documentation seems a little bit out of date.
I managed to pierce my way through this and created my [ansible-byro](https://github.com/MoritzFago/ansible-byro).
To fix some of the bugs, or my errors, I don't know. I had to fork [byro](https://github.com/MoritzFago/byro) and the plugins ([byro-gemeinützigkeit](https://github.com/MoritzFago/byro-gemeinnuetzigkeit), [byro-fints](https://github.com/MoritzFago/byro-fints) and [byro-directdebit](https://github.com/MoritzFago/byro-directdebit) we, the Toppoint e.V wanted to use.
After the software is working for us, I'll try to upstream my fixes.

My current problem ([commit-id](https://github.com/MoritzFago/byro/commit/d913bd1612bf17dfb782a62f28620ae683dc5063) seems to be something related to the `compress` step:
OS: `Debian GNU/Linux 10 (buster)`

Expected result:
No error.

Actual result:
```
sudo -iu byro python3 -m byro compress
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ ┏━o━━━━o━━━┓ This is byro v0.0.1 calling, running in production mode.   ┃
┃ ┣━━━o━━━o━━┫                                                            ┃
┃ ┣━━━━━━━━━━┫ Settings:                                                  ┃
┃ ┃   byro   ┃ Read from: /etc/byro/byro.cfg                              ┃
┃ ┗━━━━━━━━━━┛ Logging:   /opt/byro/data/logs                             ┃
┃                                                                         ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
Error parsing template /opt/byro/.local/lib/python3.7/site-packages/solo/templates/admin/solo/object_history.html: admin/object_history.html
Invalid template /opt/byro/.local/lib/python3.7/site-packages/solo/templates/admin/solo/change_form.html: 'admin_urls' is not a registered tag library. Must be one of:
bootstrap4
cache
compress
debugger_tags
extract_property
formset_tags
highlighting
i18n
indent_text
l10n
log_entry
office_tags
pagination_helper
qrcode_inline
solo_tags
static
staticfiles
syntax_color
text_tags
truncate_letters
tz
url_replace
widont
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/byro/.local/lib/python3.7/site-packages/byro/__main__.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/byro/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/byro/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/byro/.local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/byro/.local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/byro/.local/lib/python3.7/site-packages/compressor/management/commands/compress.py", line 307, in handle
    self.compress(**opts)
  File "/opt/byro/.local/lib/python3.7/site-packages/compressor/management/commands/compress.py", line 215, in compress
    "No 'compress' template tags found in templates."
compressor.exceptions.OfflineGenerationError: No 'compress' template tags found in templates.Try running compress command with --follow-links and/or--extension=EXTENSIONS
```

**Comment by MoritzFago** [comment]
The failing part seems to be, that without a MANIFEST.in, the templates aren't included in the wheel and therefore not installed.
Fixed on [my fork](https://github.com/MoritzFago/byro), all commits touching MANIFEST.in

**Comment by rixx** [comment]
Thanks for reporting – I added a MANIFEST file and also CI that will yell at us if we forget to add files to it.
