### ISSUE TITLE
Error with docker compose setup and nginx reverse-proxy

### ISSUE THREAD

**Issue by mjmucha** [byro/byro#129]
Hi!

With the help of the given documentation i tried to setup byro trough docker compose on my CentOS 8 server. I modified my compose file (and the setup.sh because i renamed the db service) for the use with nginx-proxy. As reverse-proxy i use https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion.

Sadly i encounter the following error during the setup (i ran it via sudo):
```
Successfully tagged byro_manage:latest
WARNING: Image for service manage was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/byro/byro/__main__.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/byro/byro/settings.py", line 39, in <module>
    os.makedirs(directory, exist_ok=True)
  File "/usr/local/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/var/byro/data/logs'
```
Here is my complete log of the setup: [byro-setup.log](https://github.com/byro/byro/files/4415221/byro-setup.log)

My used compose file: http://scr.mmucha.de/m5ax3
And my used setup script: http://scr.mmucha.de/ELxIW

Can someone help me?

**Comment by rixx** [comment]
I have no clue why your user would not have access to ``/var/byro/data/logs``, but I never run byro via docker. I'm leaving the issue open in case somebody else can help you, even though it does not seem to be a byro bug.

**Comment by herbetom** [comment]
I just ran into this issue. Solved it by running the following commands after it failed and then running `./byro/production/setup.sh` again to complete the setup:

```
chown 1000 byro-data/data/
chown 1000 byro-data/static.dist/
```

**Comment by GoliathLabs** [comment]
@rixx we might need to add this chown to the setup script as the docker-compose file used in production is using a custom user other than root

**Comment by rixx** [comment]
sure, happy to merge anything as long as it doesn't break non-docker setups.
