### ISSUE TITLE
Can't end membership of peter.

### ISSUE THREAD

**Issue by MoritzFago** [byro/byro#132]
Peter's nonexistend bic creates errors with the direct debit plugin

**Comment by rixx** [comment]
I assume you are talking about the test data generated by byro?

I just set up a clan byro instance, and when I went to "Vorgänge" and clicked "End membership", everything proceeded as intended. Could you please provide further details?

**Comment by MoritzFago** [comment]
I manually set the end date, if I do, I get the following backtrace.
```
Aug 10 23:09:55 byro gunicorn[299]: ERROR 2020-08-10 23:09:54,365 django.request log Internal Server Error: /members/view/1/data
Aug 10 23:09:55 byro gunicorn[299]: Traceback (most recent call last):
Aug 10 23:09:55 byro gunicorn[299]:   File "/opt/byro/.local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
Aug 10 23:09:55 byro gunicorn[299]:     response = get_response(request)
Aug 10 23:09:55 byro gunicorn[299]:   File "/opt/byro/.local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
Aug 10 23:09:55 byro gunicorn[299]:     response = self.process_exception_by_middleware(e, request)
Aug 10 23:09:55 byro gunicorn[299]:   File "/opt/byro/.local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
Aug 10 23:09:55 byro gunicorn[299]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Aug 10 23:09:55 byro gunicorn[299]:   File "/opt/byro/.local/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
Aug 10 23:09:55 byro gunicorn[299]:     return self.dispatch(request, *args, **kwargs)
Aug 10 23:09:55 byro gunicorn[299]:   File "/opt/byro/.local/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
Aug 10 23:09:55 byro gunicorn[299]:     return handler(request, *args, **kwargs)
Aug 10 23:09:55 byro gunicorn[299]:   File "/usr/lib/python3.7/contextlib.py", line 74, in inner
Aug 10 23:09:55 byro gunicorn[299]:     return func(*args, **kwds)
Aug 10 23:09:55 byro gunicorn[299]:   File "/opt/byro/.local/lib/python3.7/site-packages/byro/office/views/members.py", line 751, in post
Aug 10 23:09:55 byro gunicorn[299]:     form.save()
Aug 10 23:09:55 byro gunicorn[299]:   File "/opt/byro/.local/lib/python3.7/site-packages/django/forms/models.py", line 458, in save
Aug 10 23:09:55 byro gunicorn[299]:     self.instance.save()
Aug 10 23:09:55 byro gunicorn[299]:   File "/opt/byro/.local/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
Aug 10 23:09:55 byro gunicorn[299]:     force_update=force_update, update_fields=update_fields)
Aug 10 23:09:55 byro gunicorn[299]:   File "/opt/byro/.local/lib/python3.7/site-packages/django/db/models/base.py", line 779, in save_base
Aug 10 23:09:55 byro gunicorn[299]:     force_update, using, update_fields,
Aug 10 23:09:55 byro gunicorn[299]:   File "/opt/byro/.local/lib/python3.7/site-packages/django/db/models/base.py", line 870, in _save_table
Aug 10 23:09:55 byro gunicorn[299]:     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
Aug 10 23:09:55 byro gunicorn[299]:   File "/opt/byro/.local/lib/python3.7/site-packages/django/db/models/base.py", line 908, in _do_insert
Aug 10 23:09:55 byro gunicorn[299]:     using=using, raw=raw)
Aug 10 23:09:55 byro gunicorn[299]:   File "/opt/byro/.local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
Aug 10 23:09:55 byro gunicorn[299]:     return getattr(self.get_queryset(), name)(*args, **kwargs)
Aug 10 23:09:55 byro gunicorn[299]:   File "/opt/byro/.local/lib/python3.7/site-packages/django/db/models/query.py", line 1186, in _insert
Aug 10 23:09:55 byro gunicorn[299]:     return query.get_compiler(using=using).execute_sql(return_id)
Aug 10 23:09:55 byro gunicorn[299]:   File "/opt/byro/.local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1374, in execute_sql
Aug 10 23:09:55 byro gunicorn[299]:     for sql, params in self.as_sql():
Aug 10 23:09:55 byro gunicorn[299]:   File "/opt/byro/.local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1318, in as_sql
Aug 10 23:09:55 byro gunicorn[299]:     for obj in self.query.objs
Aug 10 23:09:55 byro gunicorn[299]:   File "/opt/byro/.local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1318, in <listcomp>
Aug 10 23:09:55 byro gunicorn[299]:     for obj in self.query.objs
Aug 10 23:09:55 byro gunicorn[299]:   File "/opt/byro/.local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1317, in <listcomp>
Aug 10 23:09:55 byro gunicorn[299]:     [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
Aug 10 23:09:55 byro gunicorn[299]:   File "/opt/byro/.local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1258, in prepare_value
Aug 10 23:09:55 byro gunicorn[299]:     value = field.get_db_prep_save(value, connection=self.connection)
Aug 10 23:09:55 byro gunicorn[299]:   File "/opt/byro/.local/lib/python3.7/site-packages/django/db/models/fields/__init__.py", line 793, in get_db_prep_save
Aug 10 23:09:55 byro gunicorn[299]:     return self.get_db_prep_value(value, connection=connection, prepared=False)
Aug 10 23:09:55 byro gunicorn[299]:   File "/opt/byro/.local/lib/python3.7/site-packages/django/db/models/fields/__init__.py", line 788, in get_db_prep_value
Aug 10 23:09:55 byro gunicorn[299]:     value = self.get_prep_value(value)
Aug 10 23:09:55 byro gunicorn[299]:   File "/opt/byro/.local/lib/python3.7/site-packages/django/db/models/fields/__init__.py", line 1825, in get_prep_value
Aug 10 23:09:55 byro gunicorn[299]:     return int(value)
Aug 10 23:09:55 byro gunicorn[299]: ValueError: invalid literal for int() with base 10: ''
```

**Comment by rixx** [comment]
It might be that with the recent changes, you have to set up the database again.
