### ISSUE TITLE
ImportError during Installation of byro and byro plugins

### ISSUE THREAD

**Issue by techn0tr0ll** [byro/byro#255]
Hello

It seems that the installation has some problems with the collections plugin. It seems that this is an issue with python 3.10 and collections ... i found some recommendations that collections.abc should now be used ?! (https://docs.python.org/3/library/collections.abc.html )

Can anyone provide support / a hotfix ?

Here is my error message: 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/byro/byro/__main__.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/byro/local/byro-fints/byro_fints/__init__.py", line 18, in ready
    from . import urls  # NOQA
  File "/byro/local/byro-fints/byro_fints/urls.py", line 3, in <module>
    from . import views
  File "/byro/local/byro-fints/byro_fints/views.py", line 21, in <module>
    from fints.client import FinTS3PinTanClient, FinTSOperations, NeedTANResponse, TransactionResponse, ResponseStatus, FinTSClientMode
  File "/usr/local/lib/python3.10/site-packages/fints-3.0.1-py3.10.egg/fints/client.py", line 14, in <module>
    from .connection import FinTSHTTPSConnection
  File "/usr/local/lib/python3.10/site-packages/fints-3.0.1-py3.10.egg/fints/connection.py", line 9, in <module>
    from .message import FinTSInstituteMessage, FinTSMessage
  File "/usr/local/lib/python3.10/site-packages/fints-3.0.1-py3.10.egg/fints/message.py", line 3, in <module>
    from .formals import SegmentSequence
  File "/usr/local/lib/python3.10/site-packages/fints-3.0.1-py3.10.egg/fints/formals.py", line 3, in <module>
    from fints.fields import *
  File "/usr/local/lib/python3.10/site-packages/fints-3.0.1-py3.10.egg/fints/fields.py", line 6, in <module>
    from fints.types import Container, SegmentSequence, TypedField
  File "/usr/local/lib/python3.10/site-packages/fints-3.0.1-py3.10.egg/fints/types.py", line 1, in <module>
    from collections import Iterable, OrderedDict
ImportError: cannot import name 'Iterable' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)
```

**Comment by rixx** [comment]
Please open the issue in the [byro-fints](/henryk/byro-fints) repository, as we can't do anything here.
