### ISSUE TITLE
Receiving these exceptions when trying to run collectstatic:

### ISSUE THREAD

**Issue by karl-baker** [byro/byro#327]
Receiving these exceptions when trying to run collectstatic:

`
python3 -m byro collectstatic
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ ┏━o━━━━o━━━┓ This is byro v0.0.2 calling, running in production mode.   ┃
┃ ┣━━━o━━━o━━┫                                                            ┃
┃ ┣━━━━━━━━━━┫ Settings:                                                  ┃
┃ ┃   byro   ┃ Read from: /etc/byro/byro.cfg                              ┃
┃ ┗━━━━━━━━━━┛ Logging:   /var/byro/data/logs                             ┃
┃                                                                         ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

You have requested to collect static files at the destination
location as specified in your settings:

    /var/byro/.local/lib/python3.10/site-packages/static.dist

This will overwrite existing files!
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes
Post-processing 'vendored/jquery-ui/jquery-ui.min.css' failed!

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/var/byro/.local/lib/python3.10/site-packages/byro/__main__.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/var/byro/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/var/byro/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/byro/.local/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/byro/.local/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/var/byro/.local/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 187, in handle
    collected = self.collect()
  File "/var/byro/.local/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 134, in collect
    raise processed
whitenoise.storage.MissingFileError: The file 'vendored/jquery-ui/images/ui-icons_444444_256x240.png' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x7fb2acff5750>.

The CSS file 'vendored/jquery-ui/jquery-ui.min.css' references a file which could not be found:
  vendored/jquery-ui/images/ui-icons_444444_256x240.png

Please check the URL references in this CSS file, particularly any
relative paths which might be pointing to the wrong location.

`

_Originally posted by @karl-baker in https://github.com/byro/byro/issues/326#issuecomment-1591936254_

**Comment by karl-baker** [comment]
Found files needed online, created and downloaded images directory, ran collect static and compress without exceptions.

Byro is now functional.

**Comment by valberg** [comment]
I'm also facing this issue - so something is up. We should get these files into byro somehow.
